'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Data.Linq
Imports System.Data.Linq.Mapping
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Reflection


<Global.System.Data.Linq.Mapping.DatabaseAttribute(Name:="PeopleCoreV5_Standard5")>  _
Partial Public Class EmployeeDataContext
	Inherits System.Data.Linq.DataContext
	
	Private Shared mappingSource As System.Data.Linq.Mapping.MappingSource = New AttributeMappingSource()
	
  #Region "Extensibility Method Definitions"
  Partial Private Sub OnCreated()
  End Sub
  #End Region
	
	Public Sub New()
		MyBase.New(Global.System.Configuration.ConfigurationManager.ConnectionStrings("PeopleCoreV5_Standard5ConnectionString").ConnectionString, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.FunctionAttribute(Name:="dbo.EEmployee_Web")>  _
	Public Function EEmployee_Web(<Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="OnlineUserNo", DbType:="Int")> ByVal onlineUserNo As System.Nullable(Of Integer), <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="PayLocNo", DbType:="Int")> ByVal payLocNo As System.Nullable(Of Integer), <Global.System.Data.Linq.Mapping.ParameterAttribute(Name:="TabIndex", DbType:="Int")> ByVal tabIndex As System.Nullable(Of Integer)) As ISingleResult(Of EEmployee_WebResult)
		Dim result As IExecuteResult = Me.ExecuteMethodCall(Me, CType(MethodInfo.GetCurrentMethod,MethodInfo), onlineUserNo, payLocNo, tabIndex)
		Return CType(result.ReturnValue,ISingleResult(Of EEmployee_WebResult))
	End Function
End Class

Partial Public Class EEmployee_WebResult
	
	Private _EmployeeNo As System.Nullable(Of Integer)
	
	Private _EmployeeCode As String
	
	Private _FullName As String
	
	Private _NickName As String
	
	Private _Email As String
	
	Private _MobileNo As String
	
	Private _BirthDate As String
	
	Private _BirthAge As System.Nullable(Of Short)
	
	Private _PositionDesc As String
	
	Private _FacilityDesc As String
	
	Private _GroupDesc As String
	
	Private _DepartmentDesc As String
	
	Private _SectionDesc As String
	
	Private _DivisionDesc As String
	
	Private _TabIndex As Integer
	
	Private _EmployeeStatDesc As String
	
	Private _EmployeeClassDesc As String
	
	Private _RankDesc As String
	
	Private _GenderDesc As String
	
	Private _CivilStatDesc As String
	
	Private _PayClassDesc As String
	
	Private _CostCenterDesc As String
	
	Private _UnitDesc As String
	
	Private _DateHired As String
	
	Private _RegularizedDate As String
	
	Private _TINNo As String
	
	Private _SSSNo As String
	
	Private _PHNo As String
	
	Private _HDMFNo As String
	
	Private _BankAccountNo As String
	
	Private _TaxExemptDesc As String
	
	Private _BankTypeDesc As String
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_EmployeeNo", DbType:="Int")>  _
	Public Property EmployeeNo() As System.Nullable(Of Integer)
		Get
			Return Me._EmployeeNo
		End Get
		Set
			If (Me._EmployeeNo.Equals(value) = false) Then
				Me._EmployeeNo = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_EmployeeCode", DbType:="VarChar(20)")>  _
	Public Property EmployeeCode() As String
		Get
			Return Me._EmployeeCode
		End Get
		Set
			If (String.Equals(Me._EmployeeCode, value) = false) Then
				Me._EmployeeCode = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_FullName", DbType:="VarChar(100)")>  _
	Public Property FullName() As String
		Get
			Return Me._FullName
		End Get
		Set
			If (String.Equals(Me._FullName, value) = false) Then
				Me._FullName = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_NickName", DbType:="VarChar(50)")>  _
	Public Property NickName() As String
		Get
			Return Me._NickName
		End Get
		Set
			If (String.Equals(Me._NickName, value) = false) Then
				Me._NickName = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Email", DbType:="VarChar(100)")>  _
	Public Property Email() As String
		Get
			Return Me._Email
		End Get
		Set
			If (String.Equals(Me._Email, value) = false) Then
				Me._Email = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_MobileNo", DbType:="VarChar(50)")>  _
	Public Property MobileNo() As String
		Get
			Return Me._MobileNo
		End Get
		Set
			If (String.Equals(Me._MobileNo, value) = false) Then
				Me._MobileNo = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_BirthDate", DbType:="VarChar(10)")>  _
	Public Property BirthDate() As String
		Get
			Return Me._BirthDate
		End Get
		Set
			If (String.Equals(Me._BirthDate, value) = false) Then
				Me._BirthDate = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_BirthAge", DbType:="SmallInt")>  _
	Public Property BirthAge() As System.Nullable(Of Short)
		Get
			Return Me._BirthAge
		End Get
		Set
			If (Me._BirthAge.Equals(value) = false) Then
				Me._BirthAge = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PositionDesc", DbType:="VarChar(100)")>  _
	Public Property PositionDesc() As String
		Get
			Return Me._PositionDesc
		End Get
		Set
			If (String.Equals(Me._PositionDesc, value) = false) Then
				Me._PositionDesc = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_FacilityDesc", DbType:="VarChar(200)")>  _
	Public Property FacilityDesc() As String
		Get
			Return Me._FacilityDesc
		End Get
		Set
			If (String.Equals(Me._FacilityDesc, value) = false) Then
				Me._FacilityDesc = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_GroupDesc", DbType:="VarChar(90)")>  _
	Public Property GroupDesc() As String
		Get
			Return Me._GroupDesc
		End Get
		Set
			If (String.Equals(Me._GroupDesc, value) = false) Then
				Me._GroupDesc = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DepartmentDesc", DbType:="VarChar(200)")>  _
	Public Property DepartmentDesc() As String
		Get
			Return Me._DepartmentDesc
		End Get
		Set
			If (String.Equals(Me._DepartmentDesc, value) = false) Then
				Me._DepartmentDesc = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SectionDesc", DbType:="VarChar(100)")>  _
	Public Property SectionDesc() As String
		Get
			Return Me._SectionDesc
		End Get
		Set
			If (String.Equals(Me._SectionDesc, value) = false) Then
				Me._SectionDesc = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DivisionDesc", DbType:="VarChar(200)")>  _
	Public Property DivisionDesc() As String
		Get
			Return Me._DivisionDesc
		End Get
		Set
			If (String.Equals(Me._DivisionDesc, value) = false) Then
				Me._DivisionDesc = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TabIndex", DbType:="Int NOT NULL")>  _
	Public Property TabIndex() As Integer
		Get
			Return Me._TabIndex
		End Get
		Set
			If ((Me._TabIndex = value)  _
						= false) Then
				Me._TabIndex = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_EmployeeStatDesc", DbType:="VarChar(50)")>  _
	Public Property EmployeeStatDesc() As String
		Get
			Return Me._EmployeeStatDesc
		End Get
		Set
			If (String.Equals(Me._EmployeeStatDesc, value) = false) Then
				Me._EmployeeStatDesc = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_EmployeeClassDesc", DbType:="VarChar(50)")>  _
	Public Property EmployeeClassDesc() As String
		Get
			Return Me._EmployeeClassDesc
		End Get
		Set
			If (String.Equals(Me._EmployeeClassDesc, value) = false) Then
				Me._EmployeeClassDesc = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_RankDesc", DbType:="VarChar(50)")>  _
	Public Property RankDesc() As String
		Get
			Return Me._RankDesc
		End Get
		Set
			If (String.Equals(Me._RankDesc, value) = false) Then
				Me._RankDesc = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_GenderDesc", DbType:="VarChar(50)")>  _
	Public Property GenderDesc() As String
		Get
			Return Me._GenderDesc
		End Get
		Set
			If (String.Equals(Me._GenderDesc, value) = false) Then
				Me._GenderDesc = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CivilStatDesc", DbType:="VarChar(100)")>  _
	Public Property CivilStatDesc() As String
		Get
			Return Me._CivilStatDesc
		End Get
		Set
			If (String.Equals(Me._CivilStatDesc, value) = false) Then
				Me._CivilStatDesc = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PayClassDesc", DbType:="VarChar(100)")>  _
	Public Property PayClassDesc() As String
		Get
			Return Me._PayClassDesc
		End Get
		Set
			If (String.Equals(Me._PayClassDesc, value) = false) Then
				Me._PayClassDesc = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CostCenterDesc", DbType:="VarChar(300)")>  _
	Public Property CostCenterDesc() As String
		Get
			Return Me._CostCenterDesc
		End Get
		Set
			If (String.Equals(Me._CostCenterDesc, value) = false) Then
				Me._CostCenterDesc = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_UnitDesc", DbType:="VarChar(100)")>  _
	Public Property UnitDesc() As String
		Get
			Return Me._UnitDesc
		End Get
		Set
			If (String.Equals(Me._UnitDesc, value) = false) Then
				Me._UnitDesc = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_DateHired", DbType:="VarChar(10)")>  _
	Public Property DateHired() As String
		Get
			Return Me._DateHired
		End Get
		Set
			If (String.Equals(Me._DateHired, value) = false) Then
				Me._DateHired = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_RegularizedDate", DbType:="VarChar(10)")>  _
	Public Property RegularizedDate() As String
		Get
			Return Me._RegularizedDate
		End Get
		Set
			If (String.Equals(Me._RegularizedDate, value) = false) Then
				Me._RegularizedDate = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TINNo", DbType:="VarChar(50)")>  _
	Public Property TINNo() As String
		Get
			Return Me._TINNo
		End Get
		Set
			If (String.Equals(Me._TINNo, value) = false) Then
				Me._TINNo = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SSSNo", DbType:="VarChar(50)")>  _
	Public Property SSSNo() As String
		Get
			Return Me._SSSNo
		End Get
		Set
			If (String.Equals(Me._SSSNo, value) = false) Then
				Me._SSSNo = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PHNo", DbType:="VarChar(50)")>  _
	Public Property PHNo() As String
		Get
			Return Me._PHNo
		End Get
		Set
			If (String.Equals(Me._PHNo, value) = false) Then
				Me._PHNo = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_HDMFNo", DbType:="VarChar(50)")>  _
	Public Property HDMFNo() As String
		Get
			Return Me._HDMFNo
		End Get
		Set
			If (String.Equals(Me._HDMFNo, value) = false) Then
				Me._HDMFNo = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_BankAccountNo", DbType:="VarChar(50)")>  _
	Public Property BankAccountNo() As String
		Get
			Return Me._BankAccountNo
		End Get
		Set
			If (String.Equals(Me._BankAccountNo, value) = false) Then
				Me._BankAccountNo = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TaxExemptDesc", DbType:="VarChar(50)")>  _
	Public Property TaxExemptDesc() As String
		Get
			Return Me._TaxExemptDesc
		End Get
		Set
			If (String.Equals(Me._TaxExemptDesc, value) = false) Then
				Me._TaxExemptDesc = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_BankTypeDesc", DbType:="VarChar(80)")>  _
	Public Property BankTypeDesc() As String
		Get
			Return Me._BankTypeDesc
		End Get
		Set
			If (String.Equals(Me._BankTypeDesc, value) = false) Then
				Me._BankTypeDesc = value
			End If
		End Set
	End Property
End Class
